[development]
address = "localhost"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
limits = { forms = 32768 }

[global.databases]
shorty_db = { url = "./shorty_db.sqlite" }
